package uk.whitecrescent.waqti.code

import java.time.Duration
import java.time.LocalDateTime

class Task(var title: String) {

    //region Class Properties

    //TODO maybe we make default state be SLEEPING, since we have to wait to be EXISTING
    /**
     * The Task State is the state in which the task is in at this point in time.
     * By default this is set to EXISTING.
     * See The Task Lifecycle Documentation for more information
     * @see TaskState
     */
    private var state = DEFAULT_TASK_STATE

    /**
     * Boolean value representing whether it is possible for this Task to be failed at any arbitrary point in time.
     * Note that this is not the same as whether it can be failed right now, however if a Task's `isFailable`
     * is `false` then it can not be failed at this point in time.
     * @see TaskState
     * @see Constraint
     */
    var isFailable = false
    //TODO fix this so that it becomes failable when it has a Constraint given to it

    /**
     * Boolean value representing whether it is possible for this Task to be killed at any arbitrary point in time.
     * Note that this is not the same as whether it can be killed right now, however if a Task's `isKillable`
     * is `false` then it can not be killed at this point in time.
     * @see TaskState
     */
    var isKillable = true

    /**
     * A Long value representing an ID for a Task.
     * Every Task has a unique identifier which is generated by means of pseudo-random number designation.
     * No 2 Tasks can have the same taskID, all taskIDs are positive Long values generated randomly.
     * The list of all currently used IDs should be stored persistently.
     * @see GSON.newID
     * @see java.util.Random.nextLong
     */
    var taskID = GSON.newID()

    //endregion

    //region Task Properties

    //TODO there has to be a better way to do this man!
    var time: Property<LocalDateTime> = DEFAULT_TIME_PROPERTY
        set(time) {
            field = time
            makeFailable(time)
        }
    var duration: Property<Duration> = DEFAULT_DURATION_PROPERTY
        set(duration) {
            field = duration
            makeFailable(duration)
        }
    var priority: Property<Priority> = DEFAULT_PRIORITY_PROPERTY
    var label: Property<Label> = DEFAULT_LABEL_PROPERTY
    var optional: Property<Boolean> = DEFAULT_OPTIONAL_PROPERTY
    var description: Property<StringBuilder> = DEFAULT_DESCRIPTION_PROPERTY
    var checkList: Property<CheckList> = DEFAULT_CHECKLIST_PROPERTY
    var deadline: Property<LocalDateTime> = DEFAULT_DEADLINE_PROPERTY
    var target: Property<String> = DEFAULT_TARGET_PROPERTY
    var before: Property<Long> = DEFAULT_BEFORE_PROPERTY
    var after: Property<Long> = DEFAULT_AFTER_PROPERTY

    //endregion

    //region Task Properties Functions

    private fun makeFailable(property: Property<*>) {
        if (!this.isFailable && property is Constraint) {
            this.isFailable = true
        }
    }

    private fun getAllProperties() = listOf(
            time,
            duration,
            priority,
            label,
            optional,
            description,
            checkList,
            deadline,
            target,
            before,
            after)

    private fun getAllConstraints() = getAllProperties().filter { it is Constraint }

    fun getAllShowingProperties() =
            getAllProperties().filter { it.isVisible }

    fun getAllShowingConstraints() =
            getAllConstraints().filter { it.isVisible }

    fun getAllUnmetAndShowingConstraints() =
            getAllConstraints().filter { !(it as Constraint).isMet && it.isVisible }

    private fun isNotConstraint(property: Property<*>) = property !is Constraint

    //endregion

    //region Property setters for chaining

    fun setTimeProperty(timeProperty: Property<LocalDateTime>): Task {
        this.time = timeProperty
        return this
    }

    fun setTimeValue(time: LocalDateTime): Task {
        this.time = Property(SHOWING, time)
        return this
    }

    fun setDurationProperty(durationProperty: Property<Duration>): Task {
        this.duration = durationProperty
        return this
    }

    fun setDurationValue(duration: Duration): Task {
        this.duration = Property(SHOWING, duration)
        return this
    }

    fun setPriorityProperty(priorityProperty: Property<Priority>): Task {
        this.priority = priorityProperty
        return this
    }

    fun setPriorityValue(priority: Priority): Task {
        this.priority = Property(SHOWING, priority)
        return this
    }

    fun setLabelProperty(labelProperty: Property<Label>): Task {
        this.label = labelProperty
        return this
    }

    fun setLabelValue(label: Label): Task {
        this.label = Property(SHOWING, label)
        return this
    }

    fun setOptionalProperty(optionalProperty: Property<Boolean>): Task {
        this.optional = optionalProperty
        return this
    }

    fun setOptionalValue(optional: Boolean): Task {
        this.optional = Property(SHOWING, optional)
        return this
    }

    fun setDescriptionProperty(descriptionProperty: Property<StringBuilder>): Task {
        this.description = descriptionProperty
        return this
    }

    fun setDescriptionValue(description: StringBuilder): Task {
        this.description = Property(SHOWING, description)
        return this
    }

    fun setChecklistProperty(checkListProperty: Property<CheckList>): Task {
        this.checkList = checkListProperty
        return this
    }

    fun setChecklistValue(checkList: CheckList): Task {
        this.checkList = Property(SHOWING, checkList)
        return this
    }

    fun setDeadlineProperty(deadlineProperty: Property<LocalDateTime>): Task {
        this.deadline = deadlineProperty
        return this
    }

    fun setDeadlineValue(deadline: LocalDateTime): Task {
        this.deadline = Property(SHOWING, deadline)
        return this
    }

    fun setTargetProperty(targetProperty: Property<String>): Task {
        this.target = targetProperty
        return this
    }

    fun setTargetValue(target: String): Task {
        this.target = Property(SHOWING, target)
        return this
    }

    fun setBeforeProperty(beforeProperty: Property<Long>): Task {
        this.before = beforeProperty
        return this
    }

    fun setBeforeProperty(beforeTask: Task): Task {
        this.before = Property(SHOWING, beforeTask.taskID)
        return this
    }

    fun setBeforeValue(before: Long): Task {
        this.before = Property(SHOWING, before)
        return this
    }

    fun setAfterProperty(afterProperty: Property<Long>): Task {
        this.after = afterProperty
        return this
    }

    fun setAfterProperty(afterTask: Task): Task {
        this.after = Property(SHOWING, afterTask.taskID)
        return this
    }

    fun setAfterValue(after: Long): Task {
        this.after = Property(SHOWING, after)
        return this
    }

    //endregion

    //region Hide Properties

    fun hideTime() {
        if (isNotConstraint(time)) {
            time = DEFAULT_TIME_PROPERTY
        } else throw IllegalStateException("Cannot hide, time is Constraint")
    }

    fun hideDuration() {
        if (isNotConstraint(duration)) {
            duration = DEFAULT_DURATION_PROPERTY
        } else throw IllegalStateException("Cannot hide, duration is Constraint")
    }

    fun hidePriority() {
        if (isNotConstraint(priority)) {
            priority = DEFAULT_PRIORITY_PROPERTY
        } else throw IllegalStateException("Cannot hide, priority is Constraint")
    }

    fun hideLabel() {
        if (isNotConstraint(label)) {
            label = DEFAULT_LABEL_PROPERTY
        } else throw IllegalStateException("Cannot hide, label is Constraint")
    }

    fun hideOptional() {
        if (isNotConstraint(optional)) {
            optional = DEFAULT_OPTIONAL_PROPERTY
        } else throw IllegalStateException("Cannot hide, optional is Constraint")
    }

    fun hideDescription() {
        if (isNotConstraint(description)) {
            description = DEFAULT_DESCRIPTION_PROPERTY
        } else throw IllegalStateException("Cannot hide, description is Constraint")
    }

    fun hideChecklist() {
        if (isNotConstraint(checkList)) {
            checkList = DEFAULT_CHECKLIST_PROPERTY
        } else throw IllegalStateException("Cannot hide, checklist is Constraint")
    }

    fun hideDeadline() {
        if (isNotConstraint(deadline)) {
            deadline = DEFAULT_DEADLINE_PROPERTY
        } else throw IllegalStateException("Cannot hide, deadline is Constraint")
    }

    fun hideTarget() {
        if (isNotConstraint(target)) {
            target = DEFAULT_TARGET_PROPERTY
        } else throw IllegalStateException("Cannot hide, target is Constraint")
    }

    fun hideBefore() {
        if (isNotConstraint(before)) {
            before = DEFAULT_BEFORE_PROPERTY
        } else throw IllegalStateException("Cannot hide, before is Constraint")
    }

    fun hideAfter() {
        if (isNotConstraint(after)) {
            after = DEFAULT_AFTER_PROPERTY
        } else throw IllegalStateException("Cannot hide, after is Constraint")
    }

    //endregion

    //region Task lifecycle

    fun getTaskState() = state

    private fun isExisting() = state == TaskState.EXISTING

    fun canKill() = isKillable &&
            isExisting() &&
            getAllUnmetAndShowingConstraints().isEmpty()


    fun canFail() = isFailable &&
            isExisting()

    //Every Task is Wait-able
    fun canWait() = getTaskState() == TaskState.FAILED

    fun fail() {
        if (state == TaskState.FAILED) {
            throw TaskStateException("Fail unsuccessful, ${this.title} is already Failed!", getTaskState())
        }
        if (!isFailable) {
            throw TaskStateException("Fail unsuccessful, ${this.title} is not Failable", getTaskState())
        } else if (canFail()) {
            state = TaskState.FAILED
        } else {
            throw TaskStateException("Fail unsuccessful, unknown reason, remember only EXISTING tasks can be failed!", getTaskState())
        }
    }

    fun sleep() {
        if (state == TaskState.SLEEPING) {
            throw TaskStateException("Sleep unsuccessful, ${this.title} is already Sleeping!", getTaskState())
        }
        if (state == TaskState.KILLED) {
            throw TaskStateException("Sleep unsuccessful, ${this.title} is Killed!", getTaskState())
        }
        if (state == TaskState.EXISTING) {
            throw TaskStateException("Sleep unsuccessful, ${this.title} is Existing!", getTaskState())
        } else if (canWait()) {
            state = TaskState.SLEEPING
        } else {
            throw TaskStateException("Sleep unsuccessful, unknown reason, remember only FAILED tasks can be slept!", getTaskState())
        }
    }


    // If a Task is killed it can be modified because it doesn't matter at all, after killed there is no other State.
    fun kill() {
        if (state == TaskState.KILLED) {
            throw TaskStateException("Kill unsuccessful, ${this.title} is already Killed!", getTaskState())
        }
        if (!isKillable) {
            throw TaskStateException("Kill unsuccessful, ${this.title} is not Killable", getTaskState())
        }
        if (!getAllUnmetAndShowingConstraints().isEmpty()) {
            throw TaskStateException("Kill unsuccessful, ${this.title} has unmet Constraints", getTaskState())
        } else if (canKill()) {
            state = TaskState.KILLED
        } else {
            throw TaskStateException("Kill unsuccessful, unknown reason, remember only EXISTING tasks can be killed!", getTaskState())
        }
    }

    //endregion

    //region Persistence Utilities

    fun saveToJSON(): Task {
        GSON.saveTask(this)
        return this
    }

    // Used by JSON only!
    constructor(
            state: TaskState,
            isFailable: Boolean,
            isKillable: Boolean,
            taskID: Long,
            time: Property<LocalDateTime>,
            duration: Property<Duration>,
            priority: Property<Priority>,
            label: Property<Label>,
            optional: Property<Boolean>,
            description: Property<StringBuilder>,
            checkList: Property<CheckList>,
            deadline: Property<LocalDateTime>,
            target: Property<String>,
            before: Property<Long>,
            after: Property<Long>,
            title: String
    ) : this(title) {
        this.state = state
        this.isFailable = isFailable
        this.isKillable = isKillable
        this.taskID = taskID
        this.time = time
        this.duration = duration
        this.priority = priority
        this.label = label
        this.optional = optional
        this.description = description
        this.checkList = checkList
        this.deadline = deadline
        this.target = target
        this.before = before
        this.after = after

    }

    //endregion

    //region Overriden from kotlin.Any

    override fun hashCode() =
            title.hashCode() + getAllShowingProperties().hashCode()

    override fun equals(other: Any?) =
            other is Task &&
                    other.title.equals(this.title) &&
                    other.getTaskState().equals(this.state) &&
                    other.getAllShowingProperties().equals(this.getAllShowingProperties())

    override fun toString(): String {
        val s = StringBuilder("Task: title = $title\n")

        getAllShowingProperties().forEach { s.append("$it \n") }

        s.append("state = $state\n\n")

        return s.toString()
    }

    //endregion
}

enum class TaskState {
    SLEEPING, // Not yet relevant or Waiting to be relevant once again, after being failed
    EXISTING,
    FAILED,
    KILLED,
    IMMORTAL // Template
}


